name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: |
            vendor
            web/modules/contrib
            web/profiles/contrib
            web/themes/contrib
            web/libraries
            web/core
            drush/Commands/contrib
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: >
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true &&
          composer config --no-plugins allow-plugins.mnsami/composer-custom-directory-installer true &&
          composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: upload
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: --exclude '.env' --exclude '.git' --exclude '.github' --exclude 'web/sites/default/files' --exclude 'private-files/*' --include 'private-files/.gitkeep' --exclude 'web/sites/default/settings.local.php' -avzr --delete
          path: ./
          remote_path: /var/www/vhosts/startklar.bayern/httpdocs/backend/
          remote_host: bahuma.io
          remote_user: startklar-bayern
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: executing post upload actions via ssh
        uses: appleboy/ssh-action@master
        with:
          host: server4.bahuma.io
          username: startklar-bayern
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: >
            export PATH="/opt/plesk/php/8.1/bin:$PATH" &&
            cd /var/www/vhosts/startklar.bayern/httpdocs/backend/web &&
            ../vendor/bin/drush updb -y &&
            ../vendor/bin/drush cim -y &&
            ../vendor/bin/drush cr &&
            ../vendor/bin/drush php-eval 'node_access_rebuild($batch_mode = TRUE);'

      - name: notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
